midi_devices:
  - loopMIDI
audio_device: VoiceMeeter


# todo
# - [ ] logo boppin'
# - [ ] opening pattern cleaner
# - [ ] disco or beach
# - [ ] ending
# - [ ] good kick effect
# - [ ] tropical color pallette
# hue shift

# - [ ] other scene than just forest
# - [x] good wobble effect
# https://www.instagram.com/p/6x41HNNnAc/
# https://www.instagram.com/p/uLmr2btnKC/
# https://www.instagram.com/p/BUwz5qfBfxf/
# https://www.instagram.com/p/BV5la2vhByx/
# https://www.instagram.com/p/BXGoDNPheAV/
# https://vimeo.com/47866056
