stages:
  - vs: "./audio/osci.vert"
    mode: "LINES"
    count: 8192
    line_width: 2
    target: "osci"
  - vs: "./audio/fft.vert"
    mode: "LINES"
    count: 8192
    line_width: 5
    target: "fft"

  - fs: ambient.frag
    target: raycast
    float: true
  - fs: ambient_gather.frag
    target: render
    float: true

  - fs: post.frag
    target: scene
  - fs: foreground.frag
    target: foreground

  - fs: composite.frag
    target: composite
    mipmap: true
  - fs: screenspace.frag

images:
  - path: images/CRT_Overlay.png
    name: overlay
  - path: images/ConcreteRough_Albedo.png
    name: albedo_tex
    filter: linear
    wrap_mode: repeat
  - path: images/ConcreteRough_Normal.png
    name: normal_tex
    filter: linear
    wrap_mode: repeat
  - path: "./images/dots.png"
    name: "dots"
  - path: "./images/text.png"
    name: "font_atlas"

audio:
  audio_samples: 4096
  attack: 0.2
  decay: 0.9
  spectrum_smooth:
    filter: linear
    mipmap: true
  spectrum:
    filter: linear
    mipmap: true
  samples:
    filter: linear
